### ISSUE TITLE
Last tag from a hex string is sometimes missing after parsing

### ISSUE THREAD

**Issue by gloomsinger79** [evsinev/ber-tlv#10]
Hi

While I was using this librairy, i've encountered a bug that prevented the parsing of the following Hex String:

BF01820114DF0105A0000000049F2201EFDF020101DF030101DF0481F8A191CB87473F29349B5D60A88B3EAEE0973AA6F1A082F358D849FDDFF9C091F899EDA9792CAF09EF28F5D22404B88A2293EEBBC1949C43BEA4D60CFD879A1539544E09E0F09F60F065B2BF2A13ECC705F3D468B9D33AE77AD9D3F19CA40F23DCF5EB7C04DC8F69EBA565B1EBCB4686CD274785530FF6F6E9EE43AA43FDB02CE00DAEC15C7B8FD6A9B394BABA419D3F6DC85E16569BE8E76989688EFEA2DF22FF7D35C043338DEAA982A02B866DE5328519EBBCD6F03CDD686673847F84DB651AB86C28CF1462562C577B853564A290C8556D818531268D25CC98A4CC6A0BDFFFDA2DCCA3A94C998559E307FDDF915006D9A987B07DDAEB3BDF050103

The node "DF05" with the length of 1 and value of "03" was not found by the API (It's at the end of the String). After some debugging I've come up with a fix that I zipped and attached to this bug entry. Not being familiar with Git Hub, i've not made a push request... sorry

Have a good day!
[BerTlvParser.zip](https://github.com/evsinev/ber-tlv/files/3596538/BerTlvParser.zip)

**Comment by evsinev** [comment]
Hi,

Thank you for your fix https://github.com/evsinev/ber-tlv/commit/1d887ab7bb49e617205b3ab5e509f44f96162342

It's been included in the 1.0-10 release.

Have a good day.
