### ISSUE TITLE
0 length Ber TLV tag got drop when using BerTlvBuilder

### ISSUE THREAD

**Issue by bertrandmartel** [evsinev/ber-tlv#2]
Hi, thanks for your great library. I've some issue with building nested BerTLV tag. The following is working as expected : 

```java
BerTlv tlv = new BerTlv(new BerTag(0x01),new byte[]{0x06});
BerTlv some = new BerTlvBuilder()
       .addBytes(new BerTag(0xE3), new BerTlvBuilder().addBerTlv(tlv).buildArray())
       .buildTlv();
```
which gives : 
```
010106
E303010106
```
But when using 0 length BerTLV tag, the following is not working 

```java
BerTlv tlv = new BerTlv(new BerTag(0x01),new byte[]{});
BerTlv some = new BerTlvBuilder()
       .addBytes(new BerTag(0xE3), new BerTlvBuilder().addBerTlv(tlv).buildArray())
       .buildTlv();
```
I get :
```
0100
E300
```
But I'm expecting :
```
0100
E3020100
```
Thanks for your help

**Comment by bertrandmartel** [comment]
Note that I also tried with the `addEmpty` method instead of `addBerTlv` but without success

**Comment by evsinev** [comment]
Hi Bertrand, 

thank you for the bug.

For the workaround you can specify 0xE3 tag as a parameter in the BerTlvBuilder contstuctor:
```java
BerTlv tlv = new BerTlv(new BerTag(0x01), new byte[]{});
BerTlv some = new BerTlvBuilder(new BerTag(0xe3))
        .addBerTlv(tlv)
        .buildTlv();
```
It would give:
```
01 00
E3 02 01 00
``` 

Does it work for you?

**Comment by bertrandmartel** [comment]
@evsinev  Thanks for your answer, unfortunately it doesn't work. Also I'm using `new BerTlvBuilder().addBerTlv(tlv).buildArray())` to print the byte array : 

```java
BerTlv tlv = new BerTlv(new BerTag(0x01), new byte[]{});
System.out.println(HexUtils.bin2hex(new BerTlvBuilder().addBerTlv(tlv).buildArray()));

BerTlv some = new BerTlvBuilder(new BerTag(0xe3))
	.addBerTlv(tlv).buildTlv();
System.out.println(HexUtils.bin2hex(new BerTlvBuilder().addBerTlv(some).buildArray()));
```
This gives :
```
0100
E300
```
And the version we're using is 1.0-7

**Comment by evsinev** [comment]
I've got your point. 
I thought that you use BerTlvBuilder.buildArray() to create an array.

You are right BerTlvBuilder.buildTlv() returns wrong elements. It skips tags with an empty length.

I'll fix it.

**Comment by evsinev** [comment]
@bertrandmartel I've fixed it in the master. You can build the project and use 1.0-8-SNAPSHOT version in your project.

Can you check it?
If it's ok I'll release a new version.

**Comment by bertrandmartel** [comment]
@evsinev Yes it's working ! Thanks a lot for your help :+1:

**Comment by evsinev** [comment]
@bertrandmartel Great. I've just release 1.0-8 version. It'll be available in a hour once sonatype will promote it to maven-central.
