### ISSUE TITLE
Why does 'BerTlvs' have a protected constructor?

### ISSUE THREAD

**Issue by patrickfav** [evsinev/ber-tlv#3]
The builder has a constructor which accepets `BerTlvs` as param:

`public BerTlvBuilder(BerTlvs tlvs)`

however the `BerTlvs` has protected constructor - is this on purpose?

**Comment by evsinev** [comment]
To create BerTlvs you always need to use BerTlvBuilder. 
BerTlvBuilder should create a right TLV structure.

Thank you for your issue. I found that BerTlvs returns the internal List<BerTlv> tlvs. It could be dangerous if we change this list in another thread.
BerTlvs should be immutable.

**Comment by patrickfav** [comment]
Ah I see thanks. Is there any advantage of creating a wrapper of `List<BerTlv>` to just actually using `List<BerTlv>` as parameter for `BerTlvBuilder`?

**Comment by evsinev** [comment]
BerTlvs is a type with additional method find, findAdd.
We use BerTlv if we sure that a structure always contains one root element with nested children.
